# Generated by Django 4.1.1 on 2022-09-07 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='commentaires',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='montantDividended',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='resultat',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
