# Generated by Django 4.1.1 on 2022-09-08 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_stockinfo_commentaires_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockinfo',
            old_name='montantDividended',
            new_name='montantDividende',
        ),
    ]
