# Generated by Django 4.1.1 on 2022-09-05 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeAction', models.CharField(blank=True, max_length=15, null=True)),
                ('pays', models.CharField(blank=True, max_length=30, null=True)),
                ('industrie', models.CharField(blank=True, max_length=30, null=True)),
                ('resultat', models.IntegerField(blank=True, null=True)),
                ('potentiel', models.CharField(choices=[('BON', 'Bon'), ('MAUVAIS', 'Mauvais'), ('A SUIVRE', 'A Suivre')], default='A SUIVRE', max_length=9)),
                ('montantDividended', models.IntegerField(blank=True, null=True)),
                ('commentaires', models.EmailField(blank=True, max_length=75, null=True)),
                ('recordDate', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
