on:
  push:
    branches:
      - main
      - diallo
jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          coverage run --data-file=coverage-test-report.txt --branch -m pytest
          rm -rf logs_webApp.log
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: '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'
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
